// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquEvmcYvmFD06ylsqCZ7g__SGAb_es0k',
    appId: '1:1086194423847:web:e7f878b60868b21631d602',
    messagingSenderId: '1086194423847',
    projectId: 'political-think',
    authDomain: 'political-think.firebaseapp.com',
    storageBucket: 'political-think.appspot.com',
    measurementId: 'G-S9FKZQPK3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggcAxX5Q2gAiQ1R6-ghXL5MqmMmI_0JQ',
    appId: '1:1086194423847:android:c707c71b7282195c31d602',
    messagingSenderId: '1086194423847',
    projectId: 'political-think',
    storageBucket: 'political-think.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGG9WeljnVJwbKOJEKrBE_wQNYFHTSEto',
    appId: '1:1086194423847:ios:1ae5d46e15600cc531d602',
    messagingSenderId: '1086194423847',
    projectId: 'political-think',
    storageBucket: 'political-think.appspot.com',
    iosClientId:
        '1086194423847-30864i1ebosr3v7i0gejpl280v2enlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.politicalThink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGG9WeljnVJwbKOJEKrBE_wQNYFHTSEto',
    appId: '1:1086194423847:ios:1ae5d46e15600cc531d602',
    messagingSenderId: '1086194423847',
    projectId: 'political-think',
    storageBucket: 'political-think.appspot.com',
    iosClientId:
        '1086194423847-30864i1ebosr3v7i0gejpl280v2enlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.politicalThink',
  );
}
