name: Deploy Backend
on:
  push: 
    branches: [ "main" ]
    paths: 
      - 'functions/**'
      - '**/*.json'
      - '**/*.rules'
      - '.github/workflows/backend.yaml'
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_SA_GOOGLE_CREDENTIALS }}'

      - name: Install Firebase CLI and Functions dependencies
        run: |
          npm install -g firebase-tools@14.3.0
          npm install
        working-directory: ./functions # Specify again if it's not a global setting

      - name: Deploy to Firebase
        # Uses GOOGLE_APPLICATION_CREDENTIALS exported by the auth step above
        run: firebase deploy --except hosting --project political-think # Hosting deployed separately
        working-directory: ./functions